# Generated by Django 5.2.6 on 2025-10-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('student_limit', models.IntegerField()),
                ('validity', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('student_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='icmsapp.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'email'), name='unique_email_per_institution'), models.UniqueConstraint(fields=('institution', 'student_id'), name='unique_studentid_per_institution')],
            },
        ),
    ]
