# Generated by Django 5.2.6 on 2025-10-07 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icmsapp', '0002_coursetopic_coursecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icmsapp.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icmsapp.coursetopic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
