# Generated by Django 5.2.6 on 2025-10-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icmsapp', '0003_taskprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
