# Generated by Django 5.2.6 on 2025-10-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icmsapp', '0004_delete_taskprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('done', 'Done'), ('redo', 'Redo')], default='not_started', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icmsapp.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icmsapp.coursetopic')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
