# Generated by Django 5.2.6 on 2025-11-13 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icmsapp', '0006_coursetopic1_coursecontent1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}TRN$')], verbose_name='Temporary Reference Number')),
                ('registration_reason', models.CharField(choices=[('voluntary', 'Voluntary Basis'), ('mandatory', 'Mandatory')], default='voluntary', max_length=20)),
                ('commencement_date', models.DateField(verbose_name='Date of Commencement of Business')),
                ('proprietor_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$')], verbose_name='PAN Number')),
                ('aadhaar_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{4}\\s\\d{4}\\s\\d{4}$')], verbose_name='Aadhaar Number')),
                ('mobile_number', models.CharField(max_length=10)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254)),
                ('res_flat_no', models.CharField(max_length=50, verbose_name='Flat/House No')),
                ('res_floor', models.CharField(blank=True, max_length=20)),
                ('res_building', models.CharField(max_length=100)),
                ('res_street', models.CharField(max_length=100)),
                ('res_area', models.CharField(max_length=100)),
                ('res_city', models.CharField(max_length=50)),
                ('res_district', models.CharField(max_length=50)),
                ('res_state', models.CharField(choices=[('UP', 'Uttar Pradesh'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('WB', 'West Bengal')], max_length=2)),
                ('res_pincode', models.CharField(max_length=6)),
                ('bus_flat_no', models.CharField(max_length=50, verbose_name='Office No')),
                ('bus_floor', models.CharField(max_length=20)),
                ('bus_building', models.CharField(max_length=100)),
                ('bus_street', models.CharField(max_length=100)),
                ('bus_area', models.CharField(max_length=100)),
                ('bus_city', models.CharField(max_length=50)),
                ('bus_district', models.CharField(max_length=50)),
                ('bus_state', models.CharField(choices=[('UP', 'Uttar Pradesh'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('WB', 'West Bengal')], max_length=2)),
                ('bus_pincode', models.CharField(max_length=6)),
                ('bus_email', models.EmailField(max_length=254, verbose_name='Business Email')),
                ('commissionerate', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=10)),
                ('range_office', models.CharField(max_length=50, verbose_name='Range')),
                ('ward', models.CharField(max_length=10)),
                ('hsn_codes', models.CharField(max_length=200, verbose_name='HSN Codes')),
                ('filing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='quarterly', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Registration',
                'verbose_name_plural': 'GST Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
