# Generated by Django 5.2.6 on 2025-11-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icmsapp', '0007_gstregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GSTRegistration',
        ),
    ]
