# Generated by Django 5.2.6 on 2025-11-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icmsapp', '0008_delete_gstregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn', models.CharField(max_length=32, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateField(blank=True, null=True)),
                ('profile_percent', models.PositiveIntegerField(default=0)),
                ('legal_name', models.CharField(blank=True, max_length=150)),
                ('pan', models.CharField(blank=True, max_length=16)),
                ('trade_name', models.CharField(blank=True, max_length=150)),
                ('constitution', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('is_casual', models.BooleanField(default=False)),
                ('is_composition', models.BooleanField(default=False)),
                ('reason_to_register', models.CharField(blank=True, max_length=120)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('liability_date', models.DateField(blank=True, null=True)),
                ('existing_type', models.CharField(blank=True, max_length=60)),
                ('existing_reg_no', models.CharField(blank=True, max_length=60)),
                ('existing_reg_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('father_first', models.CharField(blank=True, max_length=40)),
                ('father_middle', models.CharField(blank=True, max_length=40)),
                ('father_last', models.CharField(blank=True, max_length=40)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('designation', models.CharField(blank=True, max_length=60)),
                ('din', models.CharField(blank=True, max_length=40)),
                ('pan_promoter', models.CharField(blank=True, max_length=16)),
                ('passport_no', models.CharField(blank=True, max_length=20)),
                ('aadhaar_no', models.CharField(blank=True, max_length=20)),
                ('citizen', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('tel_std', models.CharField(blank=True, max_length=8)),
                ('tel_no', models.CharField(blank=True, max_length=20)),
                ('res_building', models.CharField(blank=True, max_length=120)),
                ('res_floor', models.CharField(blank=True, max_length=40)),
                ('res_premises', models.CharField(blank=True, max_length=120)),
                ('res_road', models.CharField(blank=True, max_length=120)),
                ('res_locality', models.CharField(blank=True, max_length=120)),
                ('res_country', models.CharField(blank=True, max_length=60)),
                ('res_state_name', models.CharField(blank=True, max_length=60)),
                ('res_district_name', models.CharField(blank=True, max_length=60)),
                ('res_pincode', models.CharField(blank=True, max_length=10)),
                ('photo_name', models.CharField(blank=True, max_length=120)),
                ('also_authorized_signatory', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
