# Generated by Django 5.2.6 on 2026-01-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icmsapp', '0009_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic_type', models.CharField(choices=[('Reading', 'Reading'), ('Video', 'Video'), ('Task', 'Task')], max_length=20)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='course_pdfs/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('task_info', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icmsapp.coursetopic2')),
            ],
        ),
    ]
